//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIT_Organizer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        public int ComputerID { get; set; }
        public string ComputerName { get; set; }
        public string IPAddress { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
