//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIT_Organizer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaptopIssuance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LaptopIssuance()
        {
            this.Device = new HashSet<Device>();
        }
    
        public int IssuanceID { get; set; }
        public System.DateTime DateIssuance { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string StatusID { get; set; }
        public int EmployeeIDIssuedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Device { get; set; }
    }
}
