//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Request_Refill.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartridge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cartridge()
        {
            this.Printer = new HashSet<Printer>();
        }
    
        public int CartridgeID { get; set; }
        public Nullable<int> PrinterID { get; set; }
        public int CartridgeModelID { get; set; }
        public string CartridgeNumber { get; set; }
        public int StatusID { get; set; }
        public int CartridgeTypeID { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> NumberOfRefills { get; set; }
        public Nullable<System.DateTime> LastDateOfRefill { get; set; }
    
        public virtual CartridgeStatus CartridgeStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Printer> Printer { get; set; }
    }
}
