//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Request_Refill.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartridge
    {
        public int CartridgeID { get; set; }
        public Nullable<int> PrinterID { get; set; }
        public int CartridgeModelID { get; set; }
        public string CartridgeNumber { get; set; }
        public int StatusID { get; set; }
        public int CartridgeTypeID { get; set; }
    
        public virtual CartridgeModel CartridgeModel { get; set; }
        public virtual Printer Printer { get; set; }
        public virtual CartridgeStatus CartridgeStatus { get; set; }
        public virtual CartridgeType CartridgeType { get; set; }
    }
}
