//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Request_Refill.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLIT
    {
        public int EmployeeID { get; set; }
        public int EmployeePositionID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
