//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Request_Refill.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LitDBEntities : DbContext
    {
        public LitDBEntities()
            : base("name=LitDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cabinet> Cabinet { get; set; }
        public virtual DbSet<Cartridge> Cartridge { get; set; }
        public virtual DbSet<CartridgeStatus> CartridgeStatus { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Printer> Printer { get; set; }
        public virtual DbSet<vCabinetPrinters> vCabinetPrinters { get; set; }
        public virtual DbSet<vCartridgeReport> vCartridgeReport { get; set; }
    
        public virtual ObjectResult<GetCabinetsWithPrinters_Result> GetCabinetsWithPrinters()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCabinetsWithPrinters_Result>("GetCabinetsWithPrinters");
        }
    
        public virtual ObjectResult<GetEmployeesInCabinet_Result> GetEmployeesInCabinet(Nullable<int> cabinetID)
        {
            var cabinetIDParameter = cabinetID.HasValue ?
                new ObjectParameter("CabinetID", cabinetID) :
                new ObjectParameter("CabinetID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmployeesInCabinet_Result>("GetEmployeesInCabinet", cabinetIDParameter);
        }
    
        public virtual ObjectResult<GetPrintersInCabinet_Result> GetPrintersInCabinet(Nullable<int> cabinetID)
        {
            var cabinetIDParameter = cabinetID.HasValue ?
                new ObjectParameter("CabinetID", cabinetID) :
                new ObjectParameter("CabinetID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPrintersInCabinet_Result>("GetPrintersInCabinet", cabinetIDParameter);
        }
    }
}
