//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Request_Refill.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printer
    {
        public int PrinterID { get; set; }
        public int NumbersOfRepairs { get; set; }
        public Nullable<int> CartridgeID { get; set; }
        public Nullable<int> PrinterStatusID { get; set; }
    
        public virtual Cartridge Cartridge { get; set; }
        public virtual Device Device { get; set; }
    }
}
