//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Request_Refill.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCabinetPrinters
    {
        public int CabinetID { get; set; }
        public string CabinetName { get; set; }
        public string BuildingName { get; set; }
        public int PrinterDeviceID { get; set; }
        public string PrinterModel { get; set; }
        public string PrinterInventoryNumber { get; set; }
    }
}
