//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Request_Refill.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCartridgeReport
    {
        public int CartridgeID { get; set; }
        public string Номер_картриджа { get; set; }
        public string Модель_картриджа { get; set; }
        public string Производитель { get; set; }
        public string Тип_картриджа { get; set; }
        public string Статус { get; set; }
        public string Установлен_в { get; set; }
        public Nullable<int> Емкость { get; set; }
        public Nullable<int> Количество_заправок { get; set; }
        public Nullable<System.DateTime> Дата_последней_заправки { get; set; }
        public string Местоположение { get; set; }
    }
}
