//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkTrack_Report.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartridgeReplacement_Log
    {
        public int ReplacementID { get; set; }
        public int OldCartridgeID { get; set; }
        public int NewCartridgeID { get; set; }
        public int PrinterID { get; set; }
        public int EmployeeLitID { get; set; }
        public int ReasonID { get; set; }
        public string Comment { get; set; }
    
        public virtual Cartridge Cartridge { get; set; }
        public virtual Cartridge Cartridge1 { get; set; }
        public virtual Printer Printer { get; set; }
        public virtual ReasonForReplacement ReasonForReplacement { get; set; }
    }
}
