//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkTrack_Report.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int DeviceID { get; set; }
        public int DeviceTypeID { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string Characteristics { get; set; }
        public string InventoryNumber { get; set; }
        public string SerialNumber { get; set; }
        public string DeviceName
        {
            get
            {
                return $"{Manufacturer} {Model} ({DeviceID})";
            }
        }
        public Nullable<int> CabinetID { get; set; }
   
        public virtual Cabinet Cabinet { get; set; }
        public virtual Printer Printer { get; set; }
    }
}
