//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkTrack.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int Id { get; set; }
        public int DeviceTypeId { get; set; }
        public string Characteristics { get; set; }
        public string InventoryNumber { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> DeviceModelId { get; set; }
    
        public virtual DeviceModel DeviceModel { get; set; }
        public virtual DeviceType DeviceType { get; set; }
        public virtual Room Room { get; set; }
        public virtual Printer Printer { get; set; }
    }
}
