//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkTrack_Report.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.Cabinet = new HashSet<Cabinet>();
        }
    
        public int DeviceID { get; set; }
        public int DeviceTypeID { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string Characteristics { get; set; }
        public string InventoryNumber { get; set; }
        public string SerialNumber { get; set; }
        public string DeviceName
        {
            get
            {
                return $"{Manufacturer} {Model}";
            }
        }

        public virtual Printer Printer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cabinet> Cabinet { get; set; }
    }
}
