//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkTrack_Report.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LitDBEntities : DbContext
    {
        public LitDBEntities()
            : base("name=LitDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cabinet> Cabinet { get; set; }
        public virtual DbSet<Cartridge> Cartridge { get; set; }
        public virtual DbSet<CartridgeModel> CartridgeModel { get; set; }
        public virtual DbSet<CartridgeReplacement_Log> CartridgeReplacement_Log { get; set; }
        public virtual DbSet<CartridgeStatus> CartridgeStatus { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmployeeLIT> EmployeeLIT { get; set; }
        public virtual DbSet<ReasonForReplacement> ReasonForReplacement { get; set; }
        public virtual DbSet<Printer> Printer { get; set; }
    }
}
