//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Request_Refill.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrinterModel
    {
        public int PrinterModelID { get; set; }
        public string ModelName { get; set; }
        public string Manufacturer { get; set; }
    }
}
