//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkTrack_Report.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Printer()
        {
            this.CartridgeReplacement_Log = new HashSet<CartridgeReplacement_Log>();
            this.CartridgeModel = new HashSet<CartridgeModel>();
        }
    
        public int PrinterID { get; set; }
        public int NumbersOfRepairs { get; set; }
        public Nullable<int> CartridgeID { get; set; }
        public Nullable<int> PrinterStatusID { get; set; }
        public Nullable<System.DateTime> CartridgeReplacementDate { get; set; }
        public string PrintedDocumentsList { get; set; }
    
        public virtual Cartridge Cartridge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartridgeReplacement_Log> CartridgeReplacement_Log { get; set; }
        public virtual Device Device { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartridgeModel> CartridgeModel { get; set; }
    }
}
